/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javarpiswitch;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author mark
 */
public class MainSwitch extends javax.swing.JFrame {

    /**
     * Creates new form MainSwitch
     */
    public MainSwitch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelFloorGround = new javax.swing.JLabel();
        labelFloorSecond = new javax.swing.JLabel();
        istFloorActiveIcon = new javax.swing.JLabel();
        gndActiveIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelRoomSwitches = new javax.swing.JPanel();
        lbIconOne = new javax.swing.JLabel();
        lbIconTwo = new javax.swing.JLabel();
        lbIconThree = new javax.swing.JLabel();
        lbIconFour = new javax.swing.JLabel();
        switchOne = new javax.swing.JButton();
        switchTwo = new javax.swing.JButton();
        switchThree = new javax.swing.JButton();
        switchFour = new javax.swing.JButton();
        lbIconFive = new javax.swing.JLabel();
        lbIconSix = new javax.swing.JLabel();
        lbIconSeven = new javax.swing.JLabel();
        lbIconEight = new javax.swing.JLabel();
        switchFive = new javax.swing.JButton();
        switchSix = new javax.swing.JButton();
        switchSeven = new javax.swing.JButton();
        switchEight = new javax.swing.JButton();
        lbRoom = new javax.swing.JLabel();
        MainMenuBar = new javax.swing.JMenuBar();
        subMnuMain = new javax.swing.JMenu();
        mnuItemGroundFloor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuItemFirstFloor = new javax.swing.JMenuItem();
        subMnuAbout = new javax.swing.JMenu();
        mnuItemPinOut = new javax.swing.JMenuItem();
        mnuItemShowSchematic = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Raspberry PI  Switch Board ");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelFloorGround.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelFloorGround.setText("Ground Floor          ");

        labelFloorSecond.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelFloorSecond.setText("Second Floor          ");
        labelFloorSecond.setToolTipText("");

        istFloorActiveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N

        gndActiveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFloorSecond, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(labelFloorGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gndActiveIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(istFloorActiveIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gndActiveIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFloorGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFloorSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(istFloorActiveIcon))
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMinimumSize(new java.awt.Dimension(1266, 164));
        jPanel4.setName(""); // NOI18N

        panelRoomSwitches.setMinimumSize(new java.awt.Dimension(1230, 140));
        panelRoomSwitches.setName(""); // NOI18N
        panelRoomSwitches.setLayout(new java.awt.GridLayout(4, 4, 70, 30));

        lbIconOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconOne);

        lbIconTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconTwo);

        lbIconThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconThree);

        lbIconFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconFour);

        switchOne.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchOne.setText("ON");
        switchOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchOneActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchOne);

        switchTwo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchTwo.setText("ON");
        switchTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchTwoActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchTwo);

        switchThree.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchThree.setText("ON");
        switchThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchThreeActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchThree);

        switchFour.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchFour.setText("ON");
        switchFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchFourActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchFour);

        lbIconFive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconFive);

        lbIconSix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconSix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconSix);

        lbIconSeven.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconSeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconSeven);

        lbIconEight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off.png"))); // NOI18N
        panelRoomSwitches.add(lbIconEight);

        switchFive.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchFive.setText("ON");
        switchFive.setDoubleBuffered(true);
        switchFive.setMargin(new java.awt.Insets(5, 14, 5, 14));
        switchFive.setMinimumSize(new java.awt.Dimension(151, 70));
        switchFive.setPreferredSize(new java.awt.Dimension(151, 70));
        switchFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchFiveActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchFive);

        switchSix.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchSix.setText("ON");
        switchSix.setDoubleBuffered(true);
        switchSix.setPreferredSize(new java.awt.Dimension(151, 70));
        switchSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchSixActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchSix);

        switchSeven.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchSeven.setText("ON");
        switchSeven.setDoubleBuffered(true);
        switchSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchSevenActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchSeven);

        switchEight.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        switchEight.setText("ON");
        switchEight.setDoubleBuffered(true);
        switchEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchEightActionPerformed(evt);
            }
        });
        panelRoomSwitches.add(switchEight);

        lbRoom.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbRoom.setForeground(new java.awt.Color(51, 51, 255));
        lbRoom.setText("Room's 1 to 8");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(panelRoomSwitches, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(lbRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(panelRoomSwitches, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainMenuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        subMnuMain.setText("Select Floor");
        subMnuMain.setDelay(50);
        subMnuMain.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnuItemGroundFloor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mnuItemGroundFloor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/set21-16x16.png"))); // NOI18N
        mnuItemGroundFloor.setText("Ground Floor");
        mnuItemGroundFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGroundFloorActionPerformed(evt);
            }
        });
        subMnuMain.add(mnuItemGroundFloor);
        subMnuMain.add(jSeparator1);

        mnuItemFirstFloor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mnuItemFirstFloor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/set21-16x16.png"))); // NOI18N
        mnuItemFirstFloor.setText("Second Floor");
        mnuItemFirstFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFirstFloorActionPerformed(evt);
            }
        });
        subMnuMain.add(mnuItemFirstFloor);

        MainMenuBar.add(subMnuMain);

        subMnuAbout.setText("Help");
        subMnuAbout.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        mnuItemPinOut.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mnuItemPinOut.setText("Pinouts RPI 3B");
        mnuItemPinOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPinOutActionPerformed(evt);
            }
        });
        subMnuAbout.add(mnuItemPinOut);

        mnuItemShowSchematic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mnuItemShowSchematic.setText("Schemtic of Ports");
        mnuItemShowSchematic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemShowSchematicActionPerformed(evt);
            }
        });
        subMnuAbout.add(mnuItemShowSchematic);

        MainMenuBar.add(subMnuAbout);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemPinOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPinOutActionPerformed
        // TODO add your handling code here:
         /* Create and display the form */
        
               new PinHeaderDialog(this ,true).setVisible(true);
            
        
      
         
         
    }//GEN-LAST:event_mnuItemPinOutActionPerformed

    public void setFloor(int f)
    {
        this.intfloorSet =  f ;
    }
    
    private int getFloor()
    {
       return this.intfloorSet ; 
    }
    
    private ImageIcon getlabelOnIcon()
    {
         ImageIcon image = new ImageIcon(
                        getClass().getResource("/images/on.png"));
         return image ;
        
    }
    
    
    
     private ImageIcon getlabelOffIcon()
    {
         ImageIcon image = new ImageIcon(getClass().getResource("/images/off.png")) ;
         return image ;
        
    }
    
    private void mnuItemGroundFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGroundFloorActionPerformed
        // TODO add your handling code here:
        
      
        if(pc ==null)
        {
            pc  = new PortController();
            System.out.println("Creating new controller class");
            pc.SetFloor(PortController.GROUND_FLOOR, this) ;
            this.setLabel("Ground Floor Active", 0) ;
        }
       else if (pc !=null) {
             System.out.println("First Floor set correctly");
             this.setLabel("Ground Floor Active", 0) ;
            }
    }//GEN-LAST:event_mnuItemGroundFloorActionPerformed

    public void setActionsLights(int swnum , JButton fbutton, JLabel m_label)
    {
        if(pc !=null)
         {
        
        if(fbutton.getText().trim().equals("ON"))
             
             
             
             
               {
               fbutton.setText("OFF") ;
               pc.setLight(swnum, true) ;
               m_label.setIcon(this.getlabelOnIcon());
               }else 
                    {
                      fbutton.setText("ON");
                        pc.setLight(swnum, false) ;
                        m_label.setIcon(this.getlabelOffIcon());
                        
                    }
         }
         else 
         {
            System.out.println("Controller has not been instantiated");
         }
    }
    
    private void mnuItemFirstFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemFirstFloorActionPerformed
        // TODO add your handling code here:
       
        if(pc ==null)
        {
            pc  = new PortController();
            System.out.println("Creating new controller class");
            pc.SetFloor(PortController.FIRST_FLOOR, this) ;
            
            this.setLabel("First Floor Active", 1) ;
        }
       
        else if (pc !=null) {
             System.out.println("First Floor set correctly");
             this.setLabel("First Floor Active", 1) ;
            }
              
        
        
    }//GEN-LAST:event_mnuItemFirstFloorActionPerformed

    private void switchFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchFiveActionPerformed
        // TODO add your handling code here:
        setActionsLights(4 ,this.switchFive , this.lbIconFive) ;
    }//GEN-LAST:event_switchFiveActionPerformed

    private void switchFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchFourActionPerformed
        // TODO add your handling code here:
        setActionsLights(3 ,this.switchFour , this.lbIconFour) ;
    }//GEN-LAST:event_switchFourActionPerformed

    private void switchThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchThreeActionPerformed
        // TODO add your handling code here:

        setActionsLights(2 ,this.switchThree , this.lbIconThree) ;
    }//GEN-LAST:event_switchThreeActionPerformed

    private void switchTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchTwoActionPerformed
        // TODO add your handling code here:

        setActionsLights( 1 ,this.switchTwo ,this.lbIconTwo ) ;
    }//GEN-LAST:event_switchTwoActionPerformed

    private void switchOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchOneActionPerformed
        // TODO add your handling code here:

        setActionsLights(0, this.switchOne,this.lbIconOne) ;
    }//GEN-LAST:event_switchOneActionPerformed

    private void mnuItemShowSchematicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemShowSchematicActionPerformed
        // TODO add your handling code here:
        
     new PortSchematicDialog(this ,true).setVisible(true);
    }//GEN-LAST:event_mnuItemShowSchematicActionPerformed

    private void switchSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchSixActionPerformed
        // TODO add your handling code here:
        
         setActionsLights(5, this.switchSix,this.lbIconSix) ;
    }//GEN-LAST:event_switchSixActionPerformed

    private void switchSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchSevenActionPerformed
        // TODO add your handling code here:
        setActionsLights(6, this.switchSeven,this.lbIconSeven) ;
    }//GEN-LAST:event_switchSevenActionPerformed

    private void switchEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchEightActionPerformed
        // TODO add your handling code here:
        setActionsLights(7, this.switchEight,this.lbIconEight) ;
    }//GEN-LAST:event_switchEightActionPerformed

    public void setLabel(String floor, int level)
    {
      
        switch(level){
            case 0: // ground floor 
                labelFloorGround.setText(floor);
                labelFloorGround.setForeground(Color.BLUE);
                this.gndActiveIcon.setIcon(this.getlabelOnIcon());
                
                break ;
            case 1: 
                 
                labelFloorSecond.setText(floor);
                labelFloorSecond.setForeground(Color.BLUE);
                this.istFloorActiveIcon.setIcon(this.getlabelOnIcon());
                break ;
            case 2:
                
                
                break ;
                
            default :
               
                
                
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JLabel gndActiveIcon;
    private javax.swing.JLabel istFloorActiveIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelFloorGround;
    private javax.swing.JLabel labelFloorSecond;
    private javax.swing.JLabel lbIconEight;
    private javax.swing.JLabel lbIconFive;
    private javax.swing.JLabel lbIconFour;
    private javax.swing.JLabel lbIconOne;
    private javax.swing.JLabel lbIconSeven;
    private javax.swing.JLabel lbIconSix;
    private javax.swing.JLabel lbIconThree;
    private javax.swing.JLabel lbIconTwo;
    private javax.swing.JLabel lbRoom;
    private javax.swing.JMenuItem mnuItemFirstFloor;
    private javax.swing.JMenuItem mnuItemGroundFloor;
    private javax.swing.JMenuItem mnuItemPinOut;
    private javax.swing.JMenuItem mnuItemShowSchematic;
    private javax.swing.JPanel panelRoomSwitches;
    private javax.swing.JMenu subMnuAbout;
    private javax.swing.JMenu subMnuMain;
    private javax.swing.JButton switchEight;
    private javax.swing.JButton switchFive;
    private javax.swing.JButton switchFour;
    private javax.swing.JButton switchOne;
    private javax.swing.JButton switchSeven;
    private javax.swing.JButton switchSix;
    private javax.swing.JButton switchThree;
    private javax.swing.JButton switchTwo;
    // End of variables declaration//GEN-END:variables

    // user defined variables
    
    private PortController pc = null ; 
    private  int intfloorSet = 0  ;



}
